// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDti9gjxsQlVxRpAXjMyJBKk3debtdhFlk',
    appId: '1:333194760942:web:4933adbeb28933ec5019ff',
    messagingSenderId: '333194760942',
    projectId: 'travelappfinal-49f6a',
    authDomain: 'travelappfinal-49f6a.firebaseapp.com',
    storageBucket: 'travelappfinal-49f6a.firebasestorage.app',
    measurementId: 'G-J988W6WFZK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10bks1M6ADSK2Lc6Pd4KKb9aitT3dISs',
    appId: '1:333194760942:ios:b8f5e0569a8874845019ff',
    messagingSenderId: '333194760942',
    projectId: 'travelappfinal-49f6a',
    storageBucket: 'travelappfinal-49f6a.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC10bks1M6ADSK2Lc6Pd4KKb9aitT3dISs',
    appId: '1:333194760942:ios:b8f5e0569a8874845019ff',
    messagingSenderId: '333194760942',
    projectId: 'travelappfinal-49f6a',
    storageBucket: 'travelappfinal-49f6a.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDti9gjxsQlVxRpAXjMyJBKk3debtdhFlk',
    appId: '1:333194760942:web:3710b31ef3687d875019ff',
    messagingSenderId: '333194760942',
    projectId: 'travelappfinal-49f6a',
    authDomain: 'travelappfinal-49f6a.firebaseapp.com',
    storageBucket: 'travelappfinal-49f6a.firebasestorage.app',
    measurementId: 'G-CE4YPTB6EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPY6hDMCuLGtWCFoj0TxAvKC9wejrFSds',
    appId: '1:333194760942:android:8d497e25b8e2c4ba5019ff',
    messagingSenderId: '333194760942',
    projectId: 'travelappfinal-49f6a',
    storageBucket: 'travelappfinal-49f6a.firebasestorage.app',
  );

}